# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://jpyean.github.io
date_format: "ordinal"
title: 包夹也单打
subtitle: "码了个币"
description: "jpjy的个人博客"
keywords: 包夹也单打, Jpjy
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Jpjy
organization: www.bibicar.cn
organization_url: http://www.bibicar.cn
github_username: jpyean
location: Shenzhen, China
email: zhongjipiao@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: baidu

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: jpyean/jpyean.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment
comments_provider: gitment
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: jpyean
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: jpyean
    repo: jpyean
    oauth:
        client_id: 6670df4e29418b5fbf52
        client_secret: 5a01674dc631e2bb6f42863a617898f64d881e63
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-104628955-1
